modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "${mod_license}"

[[mods]]
modId = "${archives_name}"
version = "${version}"
displayName = "${mod_displayName}"
logoFile = "${mod_logoFile}"
authors = "${mod_authors}"
description = '''
${mod_description}
'''

[[dependencies."${archives_name}"]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${archives_name}"]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${archives_name}"]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"
